export { default as ShortcutBankid50 } from './ShortcutBankid50'
export { default as ShortcutChangeCompany50 } from './ShortcutChangeCompany50'
export { default as ShortcutDocuments50 } from './ShortcutDocuments50'
export { default as ShortcutFundAssortment50 } from './ShortcutFundAssortment50'
export { default as ShortcutMessages50 } from './ShortcutMessages50'
export { default as ShortcutPayment50 } from './ShortcutPayment50'
export { default as ShortcutReportDamage50 } from './ShortcutReportDamage50'
export { default as ShortcutTransfer50 } from './ShortcutTransfer50'